language: c

addons:
  apt:
    packages:
      - gcc-arm-none-eabi
      - binutils-arm-none-eabi
      - gdb-arm-none-eabi
      - libnewlib-arm-none-eabi
      
script:
  - cd Projects/Makefile && make
